# Generated by Django 3.2.5 on 2021-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('github', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=30)),
                ('certificate_name', models.CharField(max_length=40)),
                ('school_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('tasks', models.TextField()),
                ('contact_info', models.CharField(max_length=30)),
            ],
        ),
    ]
