# Generated by Django 3.2.5 on 2021-07-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_details_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_links',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='topics',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
