# Generated by Django 3.2.5 on 2021-07-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210715_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.CharField(choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Angular', 'Angular'), ('Bootstrap', 'Bootstrap'), ('Git', 'Git')], max_length=20, null=True),
        ),
    ]
