# Generated by Django 3.2.5 on 2021-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210715_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='github',
            new_name='github_link',
        ),
        migrations.AddField(
            model_name='details',
            name='country',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
