# Generated by Django 3.2.5 on 2021-07-22 18:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210715_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(default='Image', max_length=255, verbose_name='image'),
        ),
    ]
