# Generated by Django 3.2.5 on 2021-07-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='linkedin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
