# Generated by Django 3.2.5 on 2021-08-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210723_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='languages',
            new_name='technologies',
        ),
    ]
