# Generated by Django 3.2.5 on 2021-11-12 12:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('projects', '0010_auto_20210817_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Angular', 'Angular'), ('Bootstrap', 'Bootstrap'), ('Git', 'Git'), ('Javascript', 'Javascript'), ('Postgresql', 'Postgresql'), ('DjangoREST', 'DjangoREST')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
