# Generated by Django 3.2.5 on 2021-11-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20211112_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='statement',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
