# Generated by Django 3.2.5 on 2021-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20211114_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='statement',
        ),
        migrations.AddField(
            model_name='details',
            name='facebook',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='twitter',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
