# Generated by Django 3.2.5 on 2021-11-14 17:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20211114_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Angular', 'Angular'), ('Bootstrap', 'Bootstrap'), ('Git', 'Git'), ('Javascript', 'Javascript'), ('Postgresql', 'Postgresql'), ('DjangoREST', 'DjangoREST'), ('Typescript', 'Typescript'), ('APIs', 'APIs'), ('Web design', 'Web design'), ('CSS', 'CSS'), ('HTML', 'HTML')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Angular', 'Angular'), ('Bootstrap', 'Bootstrap'), ('Git', 'Git'), ('Javascript', 'Javascript'), ('Postgresql', 'Postgresql'), ('DjangoREST', 'DjangoREST'), ('Typescript', 'Typescript'), ('APIs', 'APIs'), ('Web design', 'Web design'), ('CSS', 'CSS'), ('HTML', 'HTML')], max_length=200, null=True),
        ),
    ]
