# Generated by Django 3.2.5 on 2021-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20211114_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
